services:
  api:
    build:
      context: ../..
      dockerfile: app/docker/Dockerfile
    env_file:
      - ../../.env
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5433
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "tca_chatbot"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin_tca"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tca_chatbot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: